# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3edc408ae11ee0b798f28c725f4fe7f4355c3dade457116d6958646d2db0a0bb11984505cf1be42a15eaec58a1a8be24846ba21aba19c29127264c29d45609b

test:
  secret_key_base: 8e025fa815e94321417bf5ccacafeaa3ac50a47e502e1e4cc2bf25ccb2522a530bcf620dec157246834ad2a22ce078429fce256abee2f375522574450404b62c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
